# Generated by Django 5.0.9 on 2026-09-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_warning_percent", models.FloatField(default=80)),
                ("cpu_critical_percent", models.FloatField(default=95)),
                ("ram_warning_percent", models.FloatField(default=80)),
                ("ram_critical_percent", models.FloatField(default=95)),
                ("disk_warning_percent", models.FloatField(default=85)),
                ("disk_critical_percent", models.FloatField(default=95)),
                ("battery_critical_percent", models.FloatField(default=10)),
                (
                    "device_offline_threshold_seconds",
                    models.PositiveIntegerField(default=60),
                ),
                (
                    "device_metric_retention_days",
                    models.PositiveIntegerField(default=7),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
