# Generated by Django 5.0.9 on 2026-09-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="activity_retention_days",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
