# Generated by Django 5.0.9 on 2026-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0002_systemsettings_activity_retention_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="work_hours_end",
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="work_hours_start",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="activity_retention_days",
            field=models.PositiveIntegerField(default=180),
        ),
    ]
