# Generated by Django 5.0.9 on 2026-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="category",
            field=models.CharField(
                choices=[
                    ("CPU", "CPU Usage"),
                    ("RAM", "RAM Usage"),
                    ("DISK", "Disk Usage"),
                    ("BATTERY", "Battery Level"),
                    ("CONNECTIVITY", "Connectivity"),
                    ("USB", "USB/Removable Media"),
                ],
                max_length=20,
            ),
        ),
    ]
