# Generated by Django 5.0.9 on 2026-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alter_alert_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="category",
            field=models.CharField(
                choices=[
                    ("CPU", "CPU Usage"),
                    ("RAM", "RAM Usage"),
                    ("DISK", "Disk Usage"),
                    ("BATTERY", "Battery Level"),
                    ("CONNECTIVITY", "Connectivity"),
                    ("USB", "USB/Removable Media"),
                    ("OUT_OF_HOURS", "Activity Outside Work Hours"),
                    ("DATA_EXFIL", "Possible Data Exfiltration"),
                ],
                max_length=20,
            ),
        ),
    ]
