# Generated by Django 5.0.9 on 2026-09-11 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("cpu_percent", models.FloatField(blank=True, null=True)),
                ("cpu_frequency_mhz", models.FloatField(blank=True, null=True)),
                ("ram_total_mb", models.FloatField(blank=True, null=True)),
                ("ram_used_mb", models.FloatField(blank=True, null=True)),
                ("ram_percent", models.FloatField(blank=True, null=True)),
                ("disk_total_gb", models.FloatField(blank=True, null=True)),
                ("disk_used_gb", models.FloatField(blank=True, null=True)),
                ("disk_free_gb", models.FloatField(blank=True, null=True)),
                ("disk_percent", models.FloatField(blank=True, null=True)),
                ("net_upload_kbps", models.FloatField(blank=True, null=True)),
                ("net_download_kbps", models.FloatField(blank=True, null=True)),
                ("battery_percent", models.FloatField(blank=True, null=True)),
                ("battery_charging", models.BooleanField(blank=True, null=True)),
                ("uptime_seconds", models.BigIntegerField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-recorded_at"],
                        name="monitoring__device__ba2787_idx",
                    )
                ],
            },
        ),
    ]
