# Generated by Django 5.0.9 on 2026-09-17 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0002_enrollmenttoken_assigned_employee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowsingHistoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("browser", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=2000)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("visited_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browsing_history",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-visited_at"],
            },
        ),
        migrations.CreateModel(
            name="FileActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("MODIFIED", "Modified"),
                            ("DELETED", "Deleted"),
                            ("MOVED", "Moved"),
                        ],
                        max_length=10,
                    ),
                ),
                ("path", models.CharField(max_length=1000)),
                ("destination_path", models.CharField(blank=True, max_length=1000)),
                ("occurred_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_activity",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="AppUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=255)),
                ("window_title", models.CharField(blank=True, max_length=500)),
                ("date", models.DateField()),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_usage",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-duration_seconds"],
                "indexes": [
                    models.Index(
                        fields=["device", "-date"],
                        name="device_acti_device__4f86e5_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="appusage",
            constraint=models.UniqueConstraint(
                fields=("device", "app_name", "date"), name="unique_app_usage_per_day"
            ),
        ),
        migrations.AddIndex(
            model_name="browsinghistoryentry",
            index=models.Index(
                fields=["device", "-visited_at"], name="device_acti_device__c4b177_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="browsinghistoryentry",
            constraint=models.UniqueConstraint(
                fields=("device", "url", "visited_at"), name="unique_history_visit"
            ),
        ),
        migrations.AddIndex(
            model_name="fileactivityevent",
            index=models.Index(
                fields=["device", "-occurred_at"], name="device_acti_device__68a354_idx"
            ),
        ),
    ]
