# Generated by Django 5.0.9 on 2026-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileactivityevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Local folder (Desktop/Documents/Downloads)"),
                    ("USB", "Removable media"),
                ],
                default="LOCAL",
                max_length=10,
            ),
        ),
    ]
