# Generated by Django 5.0.9 on 2026-09-10 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="devices.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company__name", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="devices.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["branch__name", "name"],
                "unique_together": {("branch", "name")},
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("hostname", models.CharField(max_length=150)),
                ("computer_name", models.CharField(blank=True, max_length=150)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("os_name", models.CharField(blank=True, max_length=100)),
                ("os_version", models.CharField(blank=True, max_length=100)),
                ("architecture", models.CharField(blank=True, max_length=20)),
                ("cpu", models.CharField(blank=True, max_length=200)),
                ("ram", models.CharField(blank=True, max_length=100)),
                ("disk", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=150)),
                ("manufacturer", models.CharField(blank=True, max_length=150)),
                ("model", models.CharField(blank=True, max_length=150)),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("agent_version", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="OFFLINE",
                        max_length=10,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("first_registered", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="devices.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="devices.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="devices.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_registered"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential",
                        to="devices.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("position", models.CharField(blank=True, max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="devices.department",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="devices.employee",
            ),
        ),
        migrations.CreateModel(
            name="EnrollmentToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=255)),
                ("token_prefix", models.CharField(editable=False, max_length=8)),
                ("label", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_by_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_token",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="devices_dev_status_bbf58f_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["last_seen"], name="devices_dev_last_se_66ef2a_idx"
            ),
        ),
    ]
