# Generated by Django 5.0.9 on 2026-09-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttoken",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollment_tokens",
                to="devices.employee",
            ),
        ),
        migrations.AddField(
            model_name="enrollmenttoken",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollment_tokens",
                to="devices.branch",
            ),
        ),
        migrations.AddField(
            model_name="enrollmenttoken",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollment_tokens",
                to="devices.company",
            ),
        ),
        migrations.AddField(
            model_name="enrollmenttoken",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollment_tokens",
                to="devices.department",
            ),
        ),
    ]
