# Generated by Django 5.0.9 on 2026-09-19 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_enrollmenttoken_assigned_employee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=30, unique=True)),
                ("exe_file", models.FileField(upload_to="agent_releases/")),
                ("sha256", models.CharField(blank=True, editable=False, max_length=64)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("released_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-released_at"],
            },
        ),
    ]
