# Generated by Django 5.0.9 on 2026-09-14 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("install_date", models.DateField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["device", "name"], name="software_so_device__6ab171_idx"
                    )
                ],
                "unique_together": {("device", "name", "version")},
            },
        ),
    ]
