# Generated by Django 5.0.9 on 2026-09-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("accuracy_meters", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("OS", "OS Location Service"),
                            ("IP", "IP Geolocation (estimate)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-recorded_at"],
                        name="locations_l_device__4700c7_idx",
                    )
                ],
            },
        ),
    ]
